FROM node:16
FROM keymetrics/pm2:16-alpine
LABEL maintainer = "q745235"

# Copy source files from host computer to the container
COPY / /app

#install package and compile files
WORKDIR /app
RUN yarn
RUN yarn build

ENTRYPOINT ["npm", "run", "start"]

# Specify port app runs on
EXPOSE 3000